In [1]:
import pandas as pd

In [3]:
from google.colab import files

print("Please select 'ecommerce_sales_data.csv' to upload:")
uploaded = files.upload()

if 'ecommerce_sales_data.csv' in uploaded:
  print("'ecommerce_sales_data.csv' uploaded successfully!")
else:
  print("File 'ecommerce_sales_data.csv' was not uploaded or has a different name. Please try again.")

Please select 'ecommerce_sales_data.csv' to upload:

Saving ecommerce_sales_data.csv to ecommerce_sales_data.csv
'ecommerce_sales_data.csv' uploaded successfully!

In [4]:
data = pd.read_csv('ecommerce_sales_data.csv')

In [5]:
data.head()

,Order Date,Product Name,Category,Region,Quantity,Sales,Cost,Profit
0,12/31/2024,Printer,Office,North,4,3640,3291.07,348.93
1,11/27/2022,Mouse,Accessories,East,7,1197,1090.47,106.53
2,5/11/2022,Tablet,Electronics,South,5,5865,5362.27,502.73
3,3/16/2024,Mouse,Accessories,South,2,786,583.13,202.87
4,9/10/2022,Mouse,Accessories,West,1,509,405.72,103.28

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Cost          3500 non-null   float64
 7   Profit        3500 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 218.9+ KB

In [9]:
data.isnull().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Cost            0
Profit          0
dtype: int64

In [10]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

In [12]:
data.describe()

,Order Date,Quantity,Sales,Cost,Profit
count,3500,3500.000000,3500.000000,3500.000000,3500.000000
mean,2023-07-13 00:53:53.828571648,4.931714,3047.966000,2520.918797,527.047203
min,2022-01-01 00:00:00,1.000000,51.000000,40.710000,6.970000
25%,2022-10-16 18:00:00,3.000000,1049.500000,857.970000,158.695000
50%,2023-07-21 12:00:00,5.000000,2350.500000,1915.210000,361.070000
75%,2024-04-16 06:00:00,7.000000,4537.000000,3779.420000,729.125000
max,2024-12-31 00:00:00,9.000000,10782.000000,9694.700000,2946.930000
std,NaN,2.575895,2440.213237,2039.534007,504.139732

In [13]:
data['Sales'] .sum()

np.int64(10667881)

In [14]:
data['Profit'] .sum()

np.float64(1844665.21)

In [15]:
data['Quantity'] .sum()

np.int64(17261)

In [16]:
data.groupby('Category')['Sales'].sum()

Category
Accessories    4247591
Electronics    5326074
Office         1094216
Name: Sales, dtype: int64

In [17]:
data.groupby('Region')['Sales'].sum()

Region
East     2675110
North    2488773
South    2659548
West     2844450
Name: Sales, dtype: int64

In [19]:
data.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

Product Name
Camera        1177381
Monitor       1160048
Printer       1094216
Mouse         1074398
Smartphone    1069681
Smartwatch    1049211
Keyboard      1024507
Tablet        1023928
Laptop        1005873
Headphones     988638
Name: Sales, dtype: int64

In [21]:
data['Month'] = data['Order Date'].dt.month

In [22]:
data.groupby('Month')['Sales'].sum()

Month
1      967614
2      702414
3      939614
4      821876
5     1034687
6      839805
7      844940
8      924939
9      885546
10     892269
11     855075
12     959102
Name: Sales, dtype: int64